import { describe, expect, it } from 'vitest';
import { FakeIdGenerator } from '@lihen/core';
import { Money } from '@lihen/shared';
import { Brand, BrandNotFoundError, Category, CategoryNotFoundError, CreateProductHandler, GetBrandsHandler, GetCategoriesHandler, GetProductsHandler, InMemoryBrandRepository, InMemoryCategoryRepository, InMemoryProductRepository, Product, createCreateProductCommand, createGetBrandsQuery, createGetCategoriesQuery, createGetProductsQuery } from '../src';
const brands=new InMemoryBrandRepository([new Brand({id:'brand-1',name:'SAMY',normalizedName:'samy',status:'ACTIVE'})]);
const categories=new InMemoryCategoryRepository([new Category({id:'cat-1',name:'Maquillaje',normalizedName:'maquillaje',businessLine:'BEAUTY_CARE',status:'ACTIVE'})]);
describe('Brand + Category normalization slice',()=>{
 it('reads canonical brands and categories through repositories',async()=>{const brandResult=await new GetBrandsHandler(brands).execute(createGetBrandsQuery());const categoryResult=await new GetCategoriesHandler(categories).execute(createGetCategoriesQuery());expect(brandResult[0]).toMatchObject({id:'brand-1',name:'SAMY',normalizedName:'samy'});expect(categoryResult[0]).toMatchObject({id:'cat-1',name:'Maquillaje',businessLine:'BEAUTY_CARE'});});
 it('resolves product references into canonical labels',async()=>{const products=new InMemoryProductRepository([new Product({ businessLine:'BEAUTY_CARE',id:'p1',name:'Labial',brandId:'brand-1',categoryId:'cat-1',status:'ACTIVE',salePrice:new Money(20000,'COP')})]);const result=await new GetProductsHandler(products,brands,categories).execute(createGetProductsQuery());expect(result[0]).toMatchObject({brandId:'brand-1',brandName:'SAMY',categoryId:'cat-1',categoryName:'Maquillaje'});});
 it('validates canonical references before create',async()=>{const handler=new CreateProductHandler(new InMemoryProductRepository(),new FakeIdGenerator('p-new'),brands,categories);await expect(handler.execute(createCreateProductCommand({businessLine:'BEAUTY_CARE',commandId:'c1',actorId:'tester',requestedAt:new Date(),name:'Producto',brandId:'missing',salePrice:10000}))).rejects.toBeInstanceOf(BrandNotFoundError);await expect(handler.execute(createCreateProductCommand({businessLine:'BEAUTY_CARE',commandId:'c2',actorId:'tester',requestedAt:new Date(),name:'Producto',categoryId:'missing',salePrice:10000}))).rejects.toBeInstanceOf(CategoryNotFoundError);});
});
