import type{SupabaseClient}from'@supabase/supabase-js';
import type{CashClosure,CreateFinancialAccountInput,FinancialAccount,FinancialMovement,RecordCashClosureInput,RecordExpenseInput,ReverseFinancialMovementInput,TransferFundsInput}from'../domain/finance';
import type{FinanceRepository}from'../ports/finance-repository';
interface Options{readonly controlledWriteEnabled?:boolean}
function mapAccount(r:Record<string,unknown>):FinancialAccount{return{id:String(r.account_id??r.id),code:String(r.code),name:String(r.name),accountType:String(r.account_type) as FinancialAccount['accountType'],currency:'COP',status:String(r.status) as FinancialAccount['status'],balance:Number(r.balance??0)}}
function mapMovement(r:Record<string,unknown>):FinancialMovement{return{id:String(r.id),accountId:String(r.account_id),movementType:String(r.movement_type) as FinancialMovement['movementType'],amountSigned:Number(r.amount_signed),currency:'COP',occurredAt:new Date(String(r.occurred_at)),description:String(r.description),referenceType:r.reference_type?String(r.reference_type):null,referenceId:r.reference_id?String(r.reference_id):null,reversalOfId:r.reversal_of_id?String(r.reversal_of_id):null}}
function mapClosure(r:Record<string,unknown>):CashClosure{return{id:String(r.id),accountId:String(r.account_id),expectedBalance:Number(r.expected_balance),countedBalance:Number(r.counted_balance),variance:Number(r.variance),occurredAt:new Date(String(r.occurred_at)),notes:r.notes?String(r.notes):null}}
export class SupabaseFinanceRepository implements FinanceRepository{
 private readonly controlled:boolean;
 public constructor(private readonly client:SupabaseClient,o:Options={}){this.controlled=o.controlledWriteEnabled??false;}
 async listAccounts(){const{data,error}=await this.client.from('financial_account_balances').select('*').order('name');if(error)throw new Error(`Unable to read financial accounts: ${error.message}`);return((data??[])as Record<string,unknown>[]).map(mapAccount);}
 async listMovements(){const{data,error}=await this.client.from('financial_movements').select('*').order('occurred_at',{ascending:false}).limit(100);if(error)throw new Error(`Unable to read financial movements: ${error.message}`);return((data??[])as Record<string,unknown>[]).map(mapMovement);}
 async listLedgerMovements(){const{data,error}=await this.client.from('financial_movements').select('*').order('occurred_at',{ascending:true});if(error)throw new Error(`Unable to read complete financial ledger: ${error.message}`);return((data??[])as Record<string,unknown>[]).map(mapMovement);}
 async listMovementsByReferences(referenceType:string,referenceIds:readonly string[]){if(referenceIds.length===0)return[];const{data,error}=await this.client.from('financial_movements').select('*').eq('reference_type',referenceType).in('reference_id',[...referenceIds]).order('occurred_at',{ascending:false});if(error)throw new Error(`Unable to read financial movements by reference: ${error.message}`);return((data??[])as Record<string,unknown>[]).map(mapMovement);}
 async listCashClosures(){const{data,error}=await this.client.from('cash_closures').select('*').order('occurred_at',{ascending:false}).limit(50);if(error)throw new Error(`Unable to read cash closures: ${error.message}`);return((data??[])as Record<string,unknown>[]).map(mapClosure);}
 async createAccount(input:CreateFinancialAccountInput){this.assertWrite();const{error}=await this.client.rpc('create_financial_account_controlled',{p_operation_key:input.operationKey,p_id:input.id,p_code:input.code,p_name:input.name,p_account_type:input.accountType,p_currency:input.currency});if(error)throw new Error(`Unable to create financial account: ${error.message}`);const rows=await this.listAccounts();const row=rows.find(x=>x.id===input.id);if(!row)throw new Error('Created financial account could not be read.');return row;}
 async recordExpense(input:RecordExpenseInput){this.assertWrite();const{error}=await this.client.rpc('record_expense_controlled',{p_operation_key:input.operationKey,p_movement_id:input.movementId,p_account_id:input.accountId,p_amount:input.amount,p_occurred_at:input.occurredAt.toISOString(),p_description:input.description});if(error)throw new Error(`Unable to record expense: ${error.message}`);}
 async transferFunds(input:TransferFundsInput){this.assertWrite();const{error}=await this.client.rpc('transfer_financial_funds_controlled',{p_operation_key:input.operationKey,p_transfer_id:input.transferId,p_out_movement_id:input.outMovementId,p_in_movement_id:input.inMovementId,p_from_account_id:input.fromAccountId,p_to_account_id:input.toAccountId,p_amount:input.amount,p_occurred_at:input.occurredAt.toISOString(),p_description:input.description});if(error)throw new Error(`Unable to transfer funds: ${error.message}`);}
 async reverseMovement(input:ReverseFinancialMovementInput){this.assertWrite();const{error}=await this.client.rpc('reverse_financial_movement_controlled',{p_operation_key:input.operationKey,p_reversal_movement_id:input.reversalMovementId,p_original_movement_id:input.originalMovementId,p_occurred_at:input.occurredAt.toISOString(),p_reason:input.reason});if(error)throw new Error(`Unable to reverse financial movement: ${error.message}`);}
 async recordCashClosure(input:RecordCashClosureInput){this.assertWrite();const{data,error}=await this.client.rpc('record_cash_closure_controlled',{p_operation_key:input.operationKey,p_closure_id:input.closureId,p_account_id:input.accountId,p_counted_balance:input.countedBalance,p_occurred_at:input.occurredAt.toISOString(),p_notes:input.notes});if(error)throw new Error(`Unable to record cash closure: ${error.message}`);const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error('Cash closure could not be read.');return{id:String(row.closure_id),accountId:String(row.account_id),expectedBalance:Number(row.expected_balance),countedBalance:Number(row.counted_balance),variance:Number(row.variance),occurredAt:input.occurredAt,notes:input.notes};}
 private assertWrite(){if(!this.controlled)throw new Error('FINANCE_WRITE_BLOCKED');}
}
