import { getPublicHub,type PublicHubBlock } from './public-hub-api'; import { escapeHtml } from './storefront-product';
const money=(v:number|string|null)=>v==null?'':new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v));
function blockHtml(b:PublicHubBlock):string{const title=escapeHtml(b.title??'');const sub=escapeHtml(b.subtitle??'');const cta=escapeHtml(b.cta_label??'Abrir');const href=escapeHtml(b.target_url??'#');const image=b.image_url?`<img src="${escapeHtml(b.image_url)}" alt="" loading="lazy">`:'';
 if(b.block_type==='HEADING')return `<header class="hub-heading"><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</header>`;
 if(b.block_type==='TEXT')return `<div class="hub-text">${title?`<h3>${title}</h3>`:''}<p>${escapeHtml(b.body??'')}</p></div>`;
 if(b.block_type==='PRODUCT')return `<a class="hub-card hub-product" href="${href}">${image}<span><small>${escapeHtml(b.product_brand??'LIHEN')}</small><strong>${title||escapeHtml(b.product_name??'Producto')}</strong><em>${money(b.product_sale_price)}</em></span><b>${cta} →</b></a>`;
 if(b.block_type==='BANNER')return `<a class="hub-banner" href="${href}">${image}<span><strong>${title}</strong>${sub?`<small>${sub}</small>`:''}</span></a>`;
 return `<a class="hub-card" href="${href}"><span><strong>${title}</strong>${sub?`<small>${sub}</small>`:''}</span><b>${cta} →</b></a>`;}
export async function renderPublicHubPage(main:HTMLElement):Promise<void>{main.innerHTML='<section class="public-hub-page"><div class="hub-profile"><span class="hub-monogram">L</span><p>LIHEN.CO</p><h1>Beauty Care · Style</h1><span>Descubre, compra y conecta con LIHEN.</span></div><div class="hub-loading" role="status">Cargando Hub…</div></section>';try{const blocks=await getPublicHub();const host=main.querySelector<HTMLElement>('.public-hub-page');if(!host)return;host.querySelector('.hub-loading')?.remove();host.insertAdjacentHTML('beforeend',blocks.length?`<div class="hub-stack">${blocks.map(blockHtml).join('')}</div>`:'<div class="hub-empty">Pronto encontrarás aquí nuestros accesos destacados.</div>');}catch{const loading=main.querySelector<HTMLElement>('.hub-loading');if(loading)loading.textContent='No fue posible cargar este contenido. Intenta nuevamente.';}}
