import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { AdminPageHero } from '../components/AdminPageHero';
import { IntelligencePanel, type IntelligenceInsight } from '../components/IntelligencePanel';
import { OperationalNotice } from '../components/OperationalNotice';
import { SummaryStrip } from '../components/SummaryStrip';
import {
  catalogsComposition,
  inspectPdfArtifact,
  type CatalogCandidate,
  type CatalogValidationCheck,
  type CatalogVersionSummary,
  type PdfArtifactInspection,
  type StorefrontVisibilityCutoverStatus,
} from '../composition/catalogs';
import { catalogInstitutionalComposition } from '../composition/catalog-institutional';
import { evaluatePublishingReadiness } from '../domain/publishing-readiness';
import { evaluatePublishingArtifactIntegrity } from '../domain/publishing-artifact-integrity';
import { evaluatePublishingCutoverIntegrity } from '../domain/publishing-cutover-integrity';

export function CatalogsPage(){
 const [versions,setVersions]=useState<readonly CatalogVersionSummary[]>([]); const [candidates,setCandidates]=useState<readonly CatalogCandidate[]>([]); const [selected,setSelected]=useState<Set<string>>(new Set()); const [activeId,setActiveId]=useState<string>(''); const [checks,setChecks]=useState<readonly CatalogValidationCheck[]>([]); const [query,setQuery]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [form,setForm]=useState({code:'',title:'Catálogo Oficial LIHEN',versionLabel:'',sourceReference:''});
 const [artifactFile,setArtifactFile]=useState<File|null>(null); const [artifactInspection,setArtifactInspection]=useState<PdfArtifactInspection|null>(null); const [artifactBusy,setArtifactBusy]=useState(false);
 const [cutover,setCutover]=useState<StorefrontVisibilityCutoverStatus|null>(null); const [cutoverBusy,setCutoverBusy]=useState(false);
 async function refresh(){const [v,c]=await Promise.all([catalogsComposition.listVersions(),catalogsComposition.getCandidates()]);setVersions(v);setCandidates(c);if(!activeId&&v[0])setActiveId(v[0].id);}
 useEffect(()=>{refresh().catch(e=>setError(e instanceof Error?e.message:'No fue posible cargar catálogos.'));},[]);
 const eligible=useMemo(()=>candidates.filter(x=>x.eligible),[candidates]); const missing=candidates.length-eligible.length;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return candidates.filter(x=>!q||x.productName.toLowerCase().includes(q)||x.sku?.toLowerCase().includes(q)||x.brand?.toLowerCase().includes(q)||x.category?.toLowerCase().includes(q));},[candidates,query]);
 const active=versions.find(v=>v.id===activeId)??null;
 const publishingReadiness=active?evaluatePublishingReadiness({version:active,cutover}):null;
 const artifactIntegrity=active?evaluatePublishingArtifactIntegrity({catalogStatus:active.status,publicationStatus:active.publicationStatus,totalEntries:active.totalEntries,visibleEntries:active.visibleEntries,activatedAt:active.activatedAt,artifactUrl:active.artifactUrl,artifactSha256:active.artifactSha256,artifactPageCount:active.artifactPageCount,artifactSizeBytes:active.artifactSizeBytes,rendererVersion:active.rendererVersion},'catalog-renderer-v2-institutional'):null;
 const cutoverIntegrity=active?evaluatePublishingCutoverIntegrity({expectedSnapshotCount:active.visibleEntries,cutover}):null;
 const publishedVersions=versions.filter(v=>v.publicationStatus==='PUBLISHED').length;
 const draftVersions=versions.filter(v=>v.status==='DRAFT').length;
 const catalogInsights: readonly IntelligenceInsight[] = [
  artifactIntegrity?.status==='BLOCKED'
   ? {id:'catalog-artifact-integrity-blocked',severity:'CRITICAL',title:'Integridad del artefacto bloqueada',explanation:`El PDF publicado no debe avanzar a Storefront mientras existan metadatos inválidos: ${artifactIntegrity.blockers.join(', ')}.`,source:'Publishing artifact integrity'}
   : artifactIntegrity?.status==='REVIEW'
    ? {id:'catalog-artifact-integrity-review',severity:'WARNING',title:'Artefacto requiere revisión de procedencia',explanation:`La versión necesita completar evidencia antes del cutover: ${artifactIntegrity.warnings.join(', ')}.`,source:'Publishing artifact integrity'}
    : artifactIntegrity?.status==='PASS'
     ? {id:'catalog-artifact-integrity-pass',severity:'SUCCESS',title:'Artefacto PDF íntegro',explanation:'URL, SHA-256, páginas, tamaño y procedencia mínima son coherentes con una versión congelada.',source:'Publishing artifact integrity'}
     : {id:'catalog-artifact-integrity-pending',severity:'INFO',title:'Artefacto aún no congelado',explanation:'Completa el snapshot y registra el PDF final antes de evaluar su integridad.',source:'Publishing artifact integrity'},
  cutoverIntegrity?.status==='BLOCKED'
   ? {id:'catalog-cutover-integrity-blocked',severity:'CRITICAL',title:'Cutover Storefront inconsistente',explanation:`El run no debe considerarse cerrado mientras existan incoherencias: ${cutoverIntegrity.blockers.join(', ')}.`,source:'Publishing cutover integrity'}
   : cutoverIntegrity?.status==='REVIEW'
    ? {id:'catalog-cutover-integrity-review',severity:'WARNING',title:'Cutover pendiente de evidencia final',explanation:`La transición aún requiere verificación explícita: ${cutoverIntegrity.warnings.join(', ') || 'VERIFY_STOREFRONT_CUTOVER'}.`,source:'Publishing cutover integrity'}
    : cutoverIntegrity?.status==='PASS' && cutover
     ? {id:'catalog-cutover-integrity-pass',severity:'SUCCESS',title:'Cutover Storefront coherente',explanation:'Los conteos del run y, cuando aplica, las métricas VERIFIED reproducen el gate canónico de visibilidad.',source:'Publishing cutover integrity'}
     : {id:'catalog-cutover-integrity-pending',severity:'INFO',title:'Cutover aún no preparado',explanation:'La publicación web conserva un paso explícito separado del artefacto PDF.',source:'Publishing cutover integrity'},
  missing>0
   ? {id:'catalog-blocked-candidates',severity:'WARNING',title:`${missing} candidatos requieren atención`,explanation:'No entran al snapshot elegible por estado, precio o imagen. La selección masiva conserva el bloqueo.',actionLabel:'Revisar productos',targetRoute:'/products',source:'Catalog eligibility'}
   : {id:'catalog-eligibility-ready',severity:'SUCCESS',title:'Candidatos elegibles sin bloqueos',explanation:'Todos los candidatos actuales cumplen las condiciones de elegibilidad del catálogo.',source:'Catalog eligibility'},
  active?.publicationStatus==='PUBLISHED'
   ? {id:'catalog-published-snapshot',severity:'SUCCESS',title:'Snapshot publicado e inmutable',explanation:`${active.visibleEntries} entradas quedan ligadas a la versión publicada; Product Master no reescribe retrospectivamente ese PDF.`,source:'Catalog version'}
   : {id:'catalog-draft-guidance',severity:'INFO',title:'Cerrar primero el snapshot',explanation:'Antes de publicar una versión, completa selección, contenido institucional, validación y render del artefacto final.',source:'Catalog workflow'},
 ];
 useEffect(()=>{if(!activeId){setCutover(null);return;}catalogsComposition.getLatestStorefrontVisibilityCutover(activeId).then(setCutover).catch(e=>setError(e instanceof Error?e.message:'No fue posible leer el cutover web.'));},[activeId]);
 async function create(e:FormEvent){e.preventDefault();setError('');try{const id=await catalogsComposition.createDraft(form);setActiveId(id);setMessage('Versión DRAFT creada.');await refresh();}catch(x){setError(x instanceof Error?x.message:'No fue posible crear la versión.');}}
 async function saveSelection(){if(!activeId)return;try{const count=await catalogsComposition.replaceSelection(activeId,[...selected]);setMessage(`Snapshot guardado: ${count} productos.`);await refresh();}catch(x){setError(x instanceof Error?x.message:'No fue posible guardar la selección.');}}
 async function validate(){if(!activeId)return;try{const result=await catalogsComposition.validate(activeId);setChecks(result);setMessage(result.every(x=>x.status==='PASS')?'Validación PASS.':'La versión tiene validaciones pendientes.');}catch(x){setError(x instanceof Error?x.message:'No fue posible validar.');}}
 async function captureInstitutional(){if(!activeId)return;try{await catalogInstitutionalComposition.captureSnapshot(activeId);setMessage('Snapshot institucional capturado para esta versión DRAFT.');setChecks([]);}catch(x){setError(x instanceof Error?x.message:'No fue posible capturar el contenido institucional.');}}
 async function activate(){if(!activeId)return;try{await catalogsComposition.activate(activeId);setMessage('Versión ACTIVE e inmutable. La versión PDF ACTIVE anterior fue archivada automáticamente.');await refresh();}catch(x){setError(x instanceof Error?x.message:'No fue posible activar.');}}
 async function chooseArtifact(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0]??null;setArtifactFile(null);setArtifactInspection(null);setError('');if(!file)return;try{const inspection=await inspectPdfArtifact(file);setArtifactFile(file);setArtifactInspection(inspection);}catch(x){event.target.value='';setError(x instanceof Error?x.message:'No fue posible inspeccionar el PDF.');}}
 async function registerArtifact(){if(!active||!artifactFile||!artifactInspection)return;setArtifactBusy(true);setError('');try{await catalogsComposition.registerPdfArtifact(active.id,artifactFile,artifactInspection);setMessage('PDF final registrado. SHA-256 y artefacto quedaron congelados; el gate técnico de publicación fue evaluado.');setArtifactFile(null);setArtifactInspection(null);await refresh();}catch(x){setError(x instanceof Error?x.message:'No fue posible registrar el PDF final.');}finally{setArtifactBusy(false);}}
 async function prepareCutover(){if(!active)return;setCutoverBusy(true);setError('');try{const result=await catalogsComposition.prepareStorefrontVisibilityCutover(active.id,active.visibleEntries);setCutover(result);setMessage(`Cutover PREPARED: ${result.eligibleCount} elegibles · ${result.blockedCount} bloqueados.`);}catch(x){setError(x instanceof Error?x.message:'No fue posible preparar el cutover web.');}finally{setCutoverBusy(false);}}
 async function executeCutover(){if(!cutover||cutover.status!=='PREPARED')return;if(!window.confirm(`Se activará visible_on_website para ${cutover.eligibleCount} productos de la versión publicada. No se tocarán productos fuera del conjunto fuente. ¿Continuar?`))return;setCutoverBusy(true);setError('');try{const result=await catalogsComposition.executeStorefrontVisibilityCutover(cutover.runId);setCutover(result);setMessage(`Cutover EXECUTED: ${result.affectedCount} productos actualizados. Falta verificación final.`);}catch(x){setError(x instanceof Error?x.message:'No fue posible ejecutar el cutover web.');}finally{setCutoverBusy(false);}}
 async function verifyCutover(){if(!cutover||cutover.status!=='EXECUTED')return;setCutoverBusy(true);setError('');try{const result=await catalogsComposition.verifyStorefrontVisibilityCutover(cutover.runId);setCutover(result.status);const v=result.verification;setMessage(result.status.status==='VERIFIED'?`Visibilidad web verificada: ${Number(v.actual_visible_count)} productos visibles en Storefront.`:'La verificación del cutover no quedó en PASS.');}catch(x){setError(x instanceof Error?x.message:'No fue posible verificar el cutover web.');}finally{setCutoverBusy(false);}}
 function toggle(id:string){setSelected(prev=>{const next=new Set(prev);if(next.has(id)){next.delete(id);}else{next.add(id);}return next;});}
 return <section className="stack"><AdminPageHero eyebrow="PUBLICACIÓN" title="Catálogos" description="Construye versiones PDF reproducibles desde snapshots canónicos, valida su contenido y conserva cada publicación como historia inmutable." accent="gold" actions={<Link className="button-link" to="/catalogs/content">Contenido institucional</Link>} status={<span className={publishingReadiness?.status==='READY'?'status-pass':'status-alert'}>{publishingReadiness?`PUBLISHING ${publishingReadiness.status}`:'SNAPSHOT FIRST'}</span>}/>
  <SummaryStrip items={[{label:'Versiones',value:versions.length},{label:'Borradores',value:draftVersions},{label:'Publicadas',value:publishedVersions},{label:'Elegibles',value:eligible.length,detail:`${missing} bloqueados`},{label:'Publishing',value:publishingReadiness?.status??'—',detail:publishingReadiness?.stage??'Selecciona versión'},{label:'Artefacto',value:artifactIntegrity?.status??'—',detail:artifactIntegrity?.blockers[0]??artifactIntegrity?.warnings[0]??'Integridad congelada'},{label:'Cutover',value:cutoverIntegrity?.status??'—',detail:cutoverIntegrity?.blockers[0]??cutoverIntegrity?.warnings[0]??'Sin run'}]} />
  <OperationalNotice title="Publicación reproducible" tone={publishingReadiness?.status==='BLOCKED'?'warning':'info'} meta="Product Master → Eligibility → Snapshot → Catalog Version → Artifact → Storefront">El Product Master nunca publica directamente. Cada canal debe partir de una versión congelada y su readiness solo autoriza el siguiente paso explícito; no ejecuta acciones automáticamente.{publishingReadiness?.blockers.length?` Bloqueos: ${publishingReadiness.blockers.join(', ')}.`:''}{artifactIntegrity?.status==='BLOCKED'?` Integridad del artefacto: ${artifactIntegrity.blockers.join(', ')}.`:''}{cutoverIntegrity?.status==='BLOCKED'?` Integridad del cutover: ${cutoverIntegrity.blockers.join(', ')}.`:''}</OperationalNotice>
  <IntelligencePanel insights={catalogInsights} description="Prioriza bloqueos de elegibilidad y pasos de publicación sin alterar snapshots ni publicar automáticamente." />
  {message?<div className="info-state" role="status">{message}</div>:null}{error?<div className="error-state" role="alert">{error}</div>:null}
  <form className="card stack" onSubmit={create}><h2>Nueva versión PDF</h2><div className="form-grid"><label><span>Código</span><input required placeholder="LIHEN-PDF-2026-08" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label><span>Título</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>Versión</span><input required placeholder="V1" value={form.versionLabel} onChange={e=>setForm({...form,versionLabel:e.target.value})}/></label><label><span>Referencia origen</span><input value={form.sourceReference} onChange={e=>setForm({...form,sourceReference:e.target.value})}/></label></div><button type="submit">Crear DRAFT</button></form>
  <div className="card stack"><h2>Versiones</h2><select value={activeId} onChange={e=>{setActiveId(e.target.value);setChecks([]);setSelected(new Set());setArtifactFile(null);setArtifactInspection(null);}}><option value="">Seleccionar versión</option>{versions.map(v=><option key={v.id} value={v.id}>{v.code} · {v.versionLabel} · {v.publicationStatus}</option>)}</select>{active?<p><strong>{active.title}</strong> · {active.visibleEntries} entradas · estado {active.status} · publicación {active.publicationStatus}</p>:null}<div className="toolbar"><button type="button" disabled={!active||active.status!=='DRAFT'||selected.size===0} onClick={()=>void saveSelection()}>Guardar snapshot ({selected.size})</button><button type="button" disabled={!active||active.status!=='DRAFT'} onClick={()=>void captureInstitutional()}>Capturar contenido institucional</button><button type="button" disabled={!activeId} onClick={()=>void validate()}>Validar</button><button type="button" disabled={!active||active.status!=='DRAFT'||selected.size===0} onClick={()=>void activate()}>Activar versión</button>{active?.status==='ACTIVE'?<Link className="button-link" to={`/catalogs/${active.id}/render`} target="_blank" rel="noreferrer">Abrir renderer PDF</Link>:null}{active?.artifactUrl?<a className="button-link" href={active.artifactUrl} target="_blank" rel="noreferrer">Abrir PDF publicado</a>:null}</div>{checks.length?<div className="table-wrap"><table><thead><tr><th>Check</th><th>Estado</th><th>Incidencias</th></tr></thead><tbody>{checks.map(c=><tr key={c.checkName}><td>{c.checkName}</td><td>{c.status}</td><td>{c.issueCount}</td></tr>)}</tbody></table></div>:null}
   {active?.publicationStatus==='READY_TO_RENDER'?<div className="info-state stack"><strong>Registrar artefacto PDF final</strong><p>Selecciona exactamente el PDF que ya revisaste visualmente. El navegador calcula SHA-256, páginas y tamaño antes de subirlo.</p><input type="file" accept="application/pdf,.pdf" onChange={e=>void chooseArtifact(e)}/>{artifactInspection?<div><p><strong>Páginas:</strong> {artifactInspection.pageCount} · <strong>Tamaño:</strong> {artifactInspection.sizeBytes.toLocaleString('es-CO')} bytes</p><p className="mono-wrap"><strong>SHA-256:</strong> {artifactInspection.sha256}</p></div>:null}<button type="button" disabled={!artifactFile||!artifactInspection||artifactBusy} onClick={()=>void registerArtifact()}>{artifactBusy?'Registrando…':'Registrar PDF final'}</button></div>:null}
   {active?.publicationStatus==='PUBLISHED'?<div className="info-state"><strong>PDF publicado</strong><p>{active.artifactPageCount??'—'} páginas · {active.artifactSizeBytes?.toLocaleString('es-CO')??'—'} bytes · renderer {active.rendererVersion??'—'}</p><p className="mono-wrap">SHA-256: {active.artifactSha256}</p></div>:null}
   {active?.publicationStatus==='PUBLISHED'?<div className="info-state stack"><strong>Sincronización de visibilidad web</strong><p>Fuente canónica: esta versión PUBLISHED con {active.visibleEntries} productos. Solo se publican productos que sigan ACTIVE, con precio válido e imagen canónica.</p>{cutover?<div className="table-wrap"><table><tbody><tr><th>Estado</th><td>{cutover.status}</td></tr><tr><th>Fuente</th><td>{cutover.sourceCount}</td></tr><tr><th>Elegibles</th><td>{cutover.eligibleCount}</td></tr><tr><th>Bloqueados</th><td>{cutover.blockedCount}</td></tr><tr><th>Ya visibles antes</th><td>{cutover.alreadyVisibleCount}</td></tr><tr><th>Visibles fuera de fuente antes</th><td>{cutover.outsideVisibleBaselineCount}</td></tr><tr><th>Actualizados</th><td>{cutover.affectedCount}</td></tr></tbody></table></div>:null}<div className="toolbar">{!cutover?<button type="button" disabled={cutoverBusy||publishingReadiness?.nextAction!=='PREPARE_STOREFRONT_CUTOVER'||artifactIntegrity?.status!=='PASS'} onClick={()=>void prepareCutover()}>{cutoverBusy?'Preparando…':`Preparar cutover web (${active.visibleEntries})`}</button>:null}{cutover?.status==='PREPARED'?<button type="button" disabled={cutoverBusy||publishingReadiness?.status!=='READY'||publishingReadiness.nextAction!=='EXECUTE_STOREFRONT_CUTOVER'||artifactIntegrity?.status!=='PASS'||cutoverIntegrity?.status!=='PASS'} onClick={()=>void executeCutover()}>{cutoverBusy?'Ejecutando…':`Ejecutar cutover (${cutover.eligibleCount})`}</button>:null}{cutover?.status==='EXECUTED'?<button type="button" disabled={cutoverBusy||publishingReadiness?.nextAction!=='VERIFY_STOREFRONT_CUTOVER'||cutoverIntegrity?.status==='BLOCKED'} onClick={()=>void verifyCutover()}>{cutoverBusy?'Verificando…':'Verificar cutover'}</button>:null}{cutover?.status==='VERIFIED'?<strong>{cutoverIntegrity?.status==='PASS'?'PHASE5_2_STOREFRONT_VISIBILITY_CUTOVER_GATE_V1 · PASS':'PHASE5_2_STOREFRONT_VISIBILITY_CUTOVER_GATE_V1 · REVIEW'}</strong>:null}</div></div>:null}
  </div>
  <div className="card stack"><div className="toolbar"><input placeholder="Buscar producto, SKU, marca o categoría" value={query} onChange={e=>setQuery(e.target.value)}/><button type="button" onClick={()=>setSelected(new Set(eligible.map(x=>x.productId)))}>Seleccionar {eligible.length} elegibles</button><button type="button" onClick={()=>setSelected(new Set())}>Limpiar</button></div><div className="table-wrap"><table><thead><tr><th></th><th>Producto</th><th>Marca / categoría</th><th>Precio</th><th>Estado</th></tr></thead><tbody>{filtered.map(c=><tr key={c.productId}><td><input type="checkbox" disabled={!c.eligible||active?.status!=='DRAFT'} checked={selected.has(c.productId)} onChange={()=>toggle(c.productId)}/></td><td><strong>{c.productName}</strong><br/><small>{c.sku??'—'} · {c.businessLine}</small></td><td>{c.brand??'—'}<br/><small>{c.category??'—'}</small></td><td>${c.salePrice.toLocaleString('es-CO')}</td><td>{c.eligible?'ELEGIBLE':c.blockingReasons.join(', ')}</td></tr>)}</tbody></table></div></div>
 </section>;
}
