import{useEffect,useState,type FormEvent}from'react';
import{canReverseFinancialMovement,financialAccountTypes,type CashClosure,type FinancialAccount,type FinancialMovement,type FinancialAccountType}from'@lihen/finance';
import{PageHeader}from'../components/PageHeader';
import{financeComposition}from'../composition/finance';

export function FinancePage(){
 const[accounts,setAccounts]=useState<readonly FinancialAccount[]>([]);const[movements,setMovements]=useState<readonly FinancialMovement[]>([]);const[closures,setClosures]=useState<readonly CashClosure[]>([]);
 const[code,setCode]=useState('');const[name,setName]=useState('');const[type,setType]=useState<FinancialAccountType>('CASH');
 const[expenseAccount,setExpenseAccount]=useState('');const[expenseAmount,setExpenseAmount]=useState('');const[expenseDescription,setExpenseDescription]=useState('');
 const[fromAccount,setFromAccount]=useState('');const[toAccount,setToAccount]=useState('');const[transferAmount,setTransferAmount]=useState('');const[transferDescription,setTransferDescription]=useState('');
 const[closureAccount,setClosureAccount]=useState('');const[countedBalance,setCountedBalance]=useState('');const[closureNotes,setClosureNotes]=useState('');
 const[message,setMessage]=useState('');const[error,setError]=useState('');
 async function refresh(){const[a,m,c]=await Promise.all([financeComposition.repository.listAccounts(),financeComposition.repository.listMovements(),financeComposition.repository.listCashClosures()]);setAccounts(a);setMovements(m);setClosures(c);if(a.length>0){setExpenseAccount(v=>v||a[0]!.id);setFromAccount(v=>v||a[0]!.id);setToAccount(v=>v||a[Math.min(1,a.length-1)]!.id);setClosureAccount(v=>v||a[0]!.id);}}
 useEffect(()=>{refresh().catch(e=>setError(e instanceof Error?e.message:'No fue posible cargar finanzas.'));},[]);
 async function createAccount(e:FormEvent){e.preventDefault();await run(async()=>{await financeComposition.repository.createAccount({operationKey:`finance-account:${crypto.randomUUID()}`,id:financeComposition.ids.generate(),code,name,accountType:type,currency:'COP'});setCode('');setName('');return'Cuenta creada con saldo 0.';});}
 async function recordExpense(e:FormEvent){e.preventDefault();await run(async()=>{await financeComposition.repository.recordExpense({operationKey:`expense:${crypto.randomUUID()}`,movementId:financeComposition.ids.generate(),accountId:expenseAccount,amount:Number(expenseAmount),occurredAt:new Date(),description:expenseDescription});setExpenseAmount('');setExpenseDescription('');return'Egreso registrado en el ledger.';});}
 async function transfer(e:FormEvent){e.preventDefault();await run(async()=>{await financeComposition.repository.transferFunds({operationKey:`transfer:${crypto.randomUUID()}`,transferId:financeComposition.ids.generate(),outMovementId:financeComposition.ids.generate(),inMovementId:financeComposition.ids.generate(),fromAccountId:fromAccount,toAccountId:toAccount,amount:Number(transferAmount),occurredAt:new Date(),description:transferDescription});setTransferAmount('');setTransferDescription('');return'Transferencia registrada de forma balanceada.';});}
 async function closeCash(e:FormEvent){e.preventDefault();await run(async()=>{const closure=await financeComposition.repository.recordCashClosure({operationKey:`cash-closure:${crypto.randomUUID()}`,closureId:financeComposition.ids.generate(),accountId:closureAccount,countedBalance:Number(countedBalance),occurredAt:new Date(),notes:closureNotes||null});setCountedBalance('');setClosureNotes('');return`Cierre registrado. Diferencia: $${closure.variance.toLocaleString('es-CO')}.`;});}
 async function reverse(movement:FinancialMovement){const reason=window.prompt('Motivo de la reversión');if(!reason?.trim())return;await run(async()=>{await financeComposition.repository.reverseMovement({operationKey:`finance-reversal:${crypto.randomUUID()}`,reversalMovementId:financeComposition.ids.generate(),originalMovementId:movement.id,occurredAt:new Date(),reason:reason.trim()});return'Movimiento revertido mediante contramovimiento; el original se conserva.';});}
 async function run(action:()=>Promise<string>){setError('');setMessage('');try{const text=await action();setMessage(text);await refresh();}catch(e){setError(e instanceof Error?e.message:'No fue posible completar la operación financiera.');}}
 const hasAccounts=accounts.length>0;
 return <section className="stack"><PageHeader title="Caja y finanzas" description="FASE 2.8 · cuentas, ingresos de ventas, egresos, transferencias, reversiones y cierres trazables."/>
 <div className="info-state"><strong>Ledger inmutable</strong><p>Los saldos se calculan desde movimientos. Una reversión agrega un contramovimiento; no borra historia. Ventas y transferencias no se revierten desde esta pantalla porque requieren su flujo de dominio completo.</p></div>
 {financeComposition.canWrite?<>
 <form className="card stack" onSubmit={createAccount}><h2>Nueva cuenta operativa</h2><div className="form-grid"><label><span>Código</span><input required value={code} onChange={e=>setCode(e.target.value)}/></label><label><span>Nombre</span><input required value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Tipo</span><select value={type} onChange={e=>setType(e.target.value as FinancialAccountType)}>{financialAccountTypes.map(t=><option key={t} value={t}>{t}</option>)}</select></label></div><button type="submit">Crear cuenta</button></form>
 {hasAccounts?<div className="form-grid">
 <form className="card stack" onSubmit={recordExpense}><h2>Registrar egreso</h2><label><span>Cuenta</span><select required value={expenseAccount} onChange={e=>setExpenseAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · ${a.balance.toLocaleString('es-CO')}</option>)}</select></label><label><span>Valor</span><input required min="0.01" step="0.01" type="number" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)}/></label><label><span>Descripción</span><input required value={expenseDescription} onChange={e=>setExpenseDescription(e.target.value)}/></label><button type="submit">Registrar egreso</button></form>
 <form className="card stack" onSubmit={transfer}><h2>Transferir entre cuentas</h2><label><span>Desde</span><select required value={fromAccount} onChange={e=>setFromAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>Hacia</span><select required value={toAccount} onChange={e=>setToAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>Valor</span><input required min="0.01" step="0.01" type="number" value={transferAmount} onChange={e=>setTransferAmount(e.target.value)}/></label><label><span>Descripción</span><input required value={transferDescription} onChange={e=>setTransferDescription(e.target.value)}/></label><button type="submit" disabled={fromAccount===toAccount}>Transferir</button></form>
 <form className="card stack" onSubmit={closeCash}><h2>Cierre / conteo</h2><label><span>Cuenta</span><select required value={closureAccount} onChange={e=>setClosureAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>Saldo contado</span><input required step="0.01" type="number" value={countedBalance} onChange={e=>setCountedBalance(e.target.value)}/></label><label><span>Nota</span><input value={closureNotes} onChange={e=>setClosureNotes(e.target.value)}/></label><button type="submit">Registrar cierre</button></form>
 </div>:<div className="warning-state">Crea o reconcilia una cuenta antes de registrar movimientos. Los saldos legacy todavía no se importan automáticamente.</div>}
 </>:<div className="warning-state">Escritura financiera bloqueada.</div>}
 {message?<div className="info-state">{message}</div>:null}{error?<div className="error-state">{error}</div>:null}
 <div className="card stack"><h2>Cuentas</h2><div className="table-wrap"><table><thead><tr><th>Código</th><th>Nombre</th><th>Tipo</th><th>Estado</th><th>Saldo</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.code}</td><td><strong>{a.name}</strong></td><td>{a.accountType}</td><td>{a.status}</td><td>${a.balance.toLocaleString('es-CO')}</td></tr>)}</tbody></table></div>{accounts.length===0?<p>No hay cuentas canónicas todavía. Esto es correcto antes de reconciliar caja.</p>:null}</div>
 <div className="card stack"><h2>Últimos movimientos</h2><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Descripción</th><th>Valor</th><th></th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{m.occurredAt.toLocaleString()}</td><td>{m.movementType}</td><td>{m.description}</td><td>${m.amountSigned.toLocaleString('es-CO')}</td><td>{financeComposition.canWrite&&canReverseFinancialMovement(m)&&!m.reversalOfId?<button type="button" onClick={()=>void reverse(m)}>Revertir</button>:null}</td></tr>)}</tbody></table></div>{movements.length===0?<p>No hay movimientos financieros operativos todavía.</p>:null}</div>
 <div className="card stack"><h2>Últimos cierres</h2><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Cuenta</th><th>Esperado</th><th>Contado</th><th>Diferencia</th></tr></thead><tbody>{closures.map(c=><tr key={c.id}><td>{c.occurredAt.toLocaleString()}</td><td>{accounts.find(a=>a.id===c.accountId)?.name??c.accountId}</td><td>${c.expectedBalance.toLocaleString('es-CO')}</td><td>${c.countedBalance.toLocaleString('es-CO')}</td><td>${c.variance.toLocaleString('es-CO')}</td></tr>)}</tbody></table></div>{closures.length===0?<p>No hay cierres registrados todavía.</p>:null}</div>
 </section>;
}
