import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Link,useParams} from 'react-router-dom';
import type {Purchase,PurchaseItem} from '@lihen/procurement';
import {PageHeader} from '../components/PageHeader';
import {procurementComposition} from '../composition/procurement';
import {productsComposition} from '../composition/products';
interface ReceiptInput{quantity:string;cost:string}
export function PurchaseDetailPage(){const{id}=useParams();const[purchase,setPurchase]=useState<Purchase|null>(null);const[items,setItems]=useState<readonly PurchaseItem[]>([]);const[productNames,setProductNames]=useState(new Map<string,string>());const[receipt,setReceipt]=useState<Record<string,ReceiptInput>>({});const[notes,setNotes]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');
async function refresh(){if(!id)return;const[p,i,products]=await Promise.all([procurementComposition.repository.getById(id),procurementComposition.repository.listItems(id),productsComposition.repository.findAll()]);setPurchase(p);setItems(i);setProductNames(new Map(products.map(x=>[x.id,x.name])));setReceipt(Object.fromEntries(i.filter(x=>x.quantityReceived<x.quantityRequested).map(x=>[x.id,{quantity:String(x.quantityRequested-x.quantityReceived),cost:String(x.finalUnitCost??x.quotedUnitCost??'')}])));}
useEffect(()=>{refresh().catch(e=>setError(e instanceof Error?e.message:'No fue posible cargar la compra.'));},[id]);
const remaining=useMemo(()=>items.reduce((sum,x)=>sum+x.quantityRequested-x.quantityReceived,0),[items]);
async function confirm(){if(!purchase)return;setError('');setMessage('');try{await procurementComposition.confirm.execute({operationKey:`purchase-confirm:${crypto.randomUUID()}`,purchaseId:purchase.id,occurredAt:new Date()});setMessage('Compra confirmada. Las unidades ahora aparecen como PENDING_IN hasta su recepción física.');await refresh();}catch(e){setError(e instanceof Error?e.message:'No fue posible confirmar la compra.');}}
async function receive(e:FormEvent){e.preventDefault();if(!purchase)return;setError('');setMessage('');try{const lines=items.filter(x=>x.quantityReceived<x.quantityRequested).map(x=>({purchaseItemId:x.id,quantityReceived:Number(receipt[x.id]?.quantity??0),finalUnitCost:Number(receipt[x.id]?.cost??NaN)})).filter(x=>x.quantityReceived>0);await procurementComposition.receive.execute({operationKey:`purchase-receive:${crypto.randomUUID()}`,purchaseId:purchase.id,receivedAt:new Date(),notes:notes.trim()||null,lines});setMessage('Recepción registrada. PENDING_IN disminuyó y ON_HAND aumentó por las unidades recibidas.');setNotes('');await refresh();}catch(e){setError(e instanceof Error?e.message:'No fue posible registrar la recepción.');}}
if(!id)return <div className="error-state">Compra inválida.</div>;
if(!purchase)return <section className="stack"><PageHeader title="Compra" description="Detalle operativo"/>{error?<div className="error-state">{error}</div>:<p>Cargando…</p>}</section>;
return <section className="stack"><PageHeader title={`Compra ${purchase.purchaseNumber}`} description={`Estado ${purchase.status} · recepción e inventario separados de caja.`}/><div className="toolbar"><Link to="/purchases">← Volver a compras</Link>{purchase.status==='DRAFT'&&procurementComposition.canWrite?<button type="button" onClick={()=>void confirm()}>Confirmar compra</button>:null}</div>{message?<div className="info-state">{message}</div>:null}{error?<div className="error-state">{error}</div>:null}<div className="card stack"><h2>Productos</h2><div className="table-wrap"><table><thead><tr><th>Producto</th><th>Solicitado</th><th>Recibido</th><th>Pendiente</th><th>Costo cotizado</th><th>Costo final</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{productNames.get(x.productId)??x.productId}</td><td>{x.quantityRequested}</td><td>{x.quantityReceived}</td><td>{x.quantityRequested-x.quantityReceived}</td><td>{x.quotedUnitCost??'—'}</td><td>{x.finalUnitCost??'—'}</td></tr>)}</tbody></table></div></div>{['CONFIRMED','PARTIALLY_RECEIVED'].includes(purchase.status)&&remaining>0&&procurementComposition.canWrite?<form className="card stack" onSubmit={receive}><h2>Registrar recepción física</h2><p>Solo registra lo que realmente llegó. Cada recepción mueve PENDING_IN → ON_HAND y guarda el costo final.</p>{items.filter(x=>x.quantityReceived<x.quantityRequested).map(x=>{const left=x.quantityRequested-x.quantityReceived;return <div className="form-grid" key={x.id}><strong>{productNames.get(x.productId)??x.productId}</strong><label><span>Cantidad recibida (máx. {left})</span><input type="number" min="0" max={left} step="1" required value={receipt[x.id]?.quantity??''} onChange={e=>setReceipt(v=>({...v,[x.id]:{...(v[x.id]??{cost:''}),quantity:e.target.value}}))}/></label><label><span>Costo final unitario</span><input type="number" min="0" step="0.01" required value={receipt[x.id]?.cost??''} onChange={e=>setReceipt(v=>({...v,[x.id]:{...(v[x.id]??{quantity:'0'}),cost:e.target.value}}))}/></label></div>})}<label><span>Notas de recepción</span><input value={notes} onChange={e=>setNotes(e.target.value)}/></label><button type="submit">Registrar recepción</button></form>:null}<div className="info-state"><strong>Regla financiera</strong><p>Recibir mercancía todavía no paga al proveedor ni mueve efectivo/Nequi. Caja se integra en FASE 2.8.</p></div></section>}
