import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import type {Purchase} from '@lihen/procurement'; import type {Supplier} from '@lihen/suppliers';
import {PageHeader} from '../components/PageHeader'; import {procurementComposition} from '../composition/procurement'; import {suppliersComposition} from '../composition/suppliers'; import {productsComposition} from '../composition/products';
interface DraftLine{key:string;productId:string;quantity:string;cost:string}
export function PurchasesPage(){const[rows,setRows]=useState<readonly Purchase[]>([]);const[suppliers,setSuppliers]=useState<readonly Supplier[]>([]);const[products,setProducts]=useState<readonly {id:string;name:string;sku:string|null}[]>([]);const[number,setNumber]=useState('');const[supplierId,setSupplierId]=useState('');const[purchaseDate,setPurchaseDate]=useState('');const[expectedDate,setExpectedDate]=useState('');const[notes,setNotes]=useState('');const[lines,setLines]=useState<DraftLine[]>([{key:crypto.randomUUID(),productId:'',quantity:'1',cost:''}]);const[message,setMessage]=useState('');const[error,setError]=useState('');
async function refresh(){const[p,s,pr]=await Promise.all([procurementComposition.getPurchases.execute(),suppliersComposition.getSuppliers.execute(),productsComposition.repository.findAll()]);setRows(p);setSuppliers(s.filter(x=>x.status==='ACTIVE'));setProducts(pr.map(x=>({id:x.id,name:x.name,sku:x.sku??null})));}
useEffect(()=>{refresh().catch(e=>setError(e instanceof Error?e.message:'No fue posible cargar compras.'));},[]);
const supplierNames=useMemo(()=>new Map(suppliers.map(s=>[s.id,s.businessName])),[suppliers]);
function updateLine(key:string,patch:Partial<DraftLine>){setLines(v=>v.map(x=>x.key===key?{...x,...patch}:x));}
async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');try{const items=lines.map(l=>({id:procurementComposition.ids.generate(),productId:l.productId,quantityRequested:Number(l.quantity),quotedUnitCost:l.cost.trim()===''?null:Number(l.cost)}));await procurementComposition.createDraft.execute({operationKey:`purchase-draft:${crypto.randomUUID()}`,purchaseId:procurementComposition.ids.generate(),purchaseNumber:number,supplierId,purchaseDate:purchaseDate||null,expectedDate:expectedDate||null,notes:notes.trim()||null,items});setNumber('');setSupplierId('');setPurchaseDate('');setExpectedDate('');setNotes('');setLines([{key:crypto.randomUUID(),productId:'',quantity:'1',cost:''}]);setMessage('Borrador de compra creado. Todavía no afecta inventario ni caja.');await refresh();}catch(e){setError(e instanceof Error?e.message:'No fue posible crear la compra.');}}
return <section className="stack"><PageHeader title="Compras" description="FASE 2.5B · borradores de compra controlados. Confirmar, recibir mercancía y pagar son gates separados."/><div className="info-state"><strong>Sin efectos ocultos</strong><p>Crear un DRAFT no cambia ON_HAND, PENDING_IN, costos finales, facturas ni caja.</p></div>{procurementComposition.canWrite?<form className="card stack" onSubmit={submit}><h2>Nueva compra en borrador</h2><div className="form-grid"><label><span>Número / referencia</span><input required value={number} onChange={e=>setNumber(e.target.value)}/></label><label><span>Proveedor activo</span><select required value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Seleccionar…</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.businessName}</option>)}</select></label><label><span>Fecha compra</span><input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)}/></label><label><span>Fecha esperada</span><input type="date" value={expectedDate} onChange={e=>setExpectedDate(e.target.value)}/></label><label><span>Notas</span><input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><h3>Productos</h3>{lines.map((l,i)=><div className="form-grid" key={l.key}><label><span>Producto {i+1}</span><select required value={l.productId} onChange={e=>updateLine(l.key,{productId:e.target.value})}><option value="">Seleccionar…</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku?`${p.sku} · `:''}{p.name}</option>)}</select></label><label><span>Cantidad</span><input required type="number" min="1" step="1" value={l.quantity} onChange={e=>updateLine(l.key,{quantity:e.target.value})}/></label><label><span>Costo cotizado unitario</span><input type="number" min="0" step="0.01" value={l.cost} onChange={e=>updateLine(l.key,{cost:e.target.value})}/></label>{lines.length>1?<button type="button" onClick={()=>setLines(v=>v.filter(x=>x.key!==l.key))}>Quitar</button>:null}</div>)}<div className="toolbar"><button type="button" onClick={()=>setLines(v=>[...v,{key:crypto.randomUUID(),productId:'',quantity:'1',cost:''}])}>Agregar producto</button><button type="submit">Guardar borrador</button></div></form>:<div className="warning-state">Escritura de compras bloqueada.</div>}{message?<div className="info-state">{message}</div>:null}{error?<div className="error-state">{error}</div>:null}<div className="card stack"><h2>Compras registradas</h2><div className="table-wrap"><table><thead><tr><th>Número</th><th>Proveedor</th><th>Estado</th><th>Compra</th><th>Esperada</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link to={`/purchases/${r.id}`}><strong>{r.purchaseNumber}</strong></Link></td><td>{supplierNames.get(r.supplierId)??r.supplierId}</td><td>{r.status}</td><td>{r.purchaseDate??'—'}</td><td>{r.expectedDate??'—'}</td></tr>)}</tbody></table></div>{rows.length===0?<p>No hay compras canónicas todavía.</p>:null}</div></section>}
