import type { SupabaseClient } from '@supabase/supabase-js';
import type { CreatePurchaseDraftCommand } from '../application/commands/create-purchase-draft.command';
import type { ConfirmPurchaseCommand } from '../application/commands/confirm-purchase.command';
import type { ReceivePurchaseCommand } from '../application/commands/receive-purchase.command';
import type { Purchase } from '../domain/purchase';
import type { PurchaseItem } from '../domain/purchase-item';
import type { PurchaseRepository } from '../ports/purchase-repository';
interface Options { readonly controlledWriteEnabled?: boolean; }
function mapPurchase(row:Record<string,unknown>):Purchase{return{id:String(row.id),purchaseNumber:String(row.purchase_number),supplierId:String(row.supplier_id),status:String(row.status) as Purchase['status'],purchaseDate:row.purchase_date?String(row.purchase_date):null,expectedDate:row.expected_date?String(row.expected_date):null,receivedAt:row.received_at?new Date(String(row.received_at)):null,notes:row.notes?String(row.notes):null,historical:Boolean(row.is_historical),createdAt:new Date(String(row.created_at)),updatedAt:new Date(String(row.updated_at))};}
export class SupabasePurchaseRepository implements PurchaseRepository {
  private readonly controlledWriteEnabled:boolean; public constructor(private readonly client:SupabaseClient,options:Options={}){this.controlledWriteEnabled=options.controlledWriteEnabled??false;}
  public async list(){const{data,error}=await this.client.from('purchases').select('*').order('created_at',{ascending:false});if(error)throw new Error(`Unable to read purchases: ${error.message}`);return((data??[])as Record<string,unknown>[]).map(mapPurchase);}
  public async getById(id:string){const{data,error}=await this.client.from('purchases').select('*').eq('id',id).maybeSingle();if(error)throw new Error(`Unable to read purchase: ${error.message}`);return data?mapPurchase(data as Record<string,unknown>):null;}
  public async listItems(purchaseId:string):Promise<readonly PurchaseItem[]>{const{data,error}=await this.client.from('purchase_items').select('*').eq('purchase_id',purchaseId);if(error)throw new Error(`Unable to read purchase items: ${error.message}`);return((data??[])as Record<string,unknown>[]).map((r)=>({id:String(r.id),purchaseId:String(r.purchase_id),productId:String(r.product_id),quantityRequested:Number(r.quantity_requested),quantityReceived:Number(r.quantity_received),quotedUnitCost:r.quoted_unit_cost==null?null:Number(r.quoted_unit_cost),finalUnitCost:r.final_unit_cost==null?null:Number(r.final_unit_cost),createdAt:new Date(String(r.created_at)),updatedAt:new Date(String(r.updated_at))}));}
  public async createDraft(command:CreatePurchaseDraftCommand):Promise<Purchase>{if(!this.controlledWriteEnabled)throw new Error('PURCHASE_WRITE_BLOCKED');const{data,error}=await this.client.rpc('create_purchase_draft_controlled',{p_operation_key:command.operationKey,p_purchase_id:command.purchaseId,p_purchase_number:command.purchaseNumber,p_supplier_id:command.supplierId,p_purchase_date:command.purchaseDate,p_expected_date:command.expectedDate,p_notes:command.notes,p_items:command.items.map((i)=>({id:i.id,product_id:i.productId,quantity_requested:i.quantityRequested,quoted_unit_cost:i.quotedUnitCost}))});if(error)throw new Error(`Unable to create purchase draft: ${error.message}`);const row=(Array.isArray(data)?data[0]:data) as Record<string,unknown>|null;if(!row)throw new Error('Controlled purchase RPC returned no result.');return{id:String(row.id),purchaseNumber:String(row.purchase_number),supplierId:String(row.supplier_id),status:'DRAFT',purchaseDate:row.purchase_date?String(row.purchase_date):null,expectedDate:row.expected_date?String(row.expected_date):null,receivedAt:null,notes:row.notes?String(row.notes):null,historical:false,createdAt:new Date(),updatedAt:new Date()};}
  public async confirm(command:ConfirmPurchaseCommand):Promise<Purchase>{if(!this.controlledWriteEnabled)throw new Error('PURCHASE_WRITE_BLOCKED');const{error}=await this.client.rpc('confirm_purchase_controlled',{p_operation_key:command.operationKey,p_purchase_id:command.purchaseId,p_occurred_at:command.occurredAt.toISOString()});if(error)throw new Error(`Unable to confirm purchase: ${error.message}`);const purchase=await this.getById(command.purchaseId);if(!purchase)throw new Error('Confirmed purchase could not be read.');return purchase;}
  public async receive(command:ReceivePurchaseCommand):Promise<Purchase>{if(!this.controlledWriteEnabled)throw new Error('PURCHASE_WRITE_BLOCKED');const{error}=await this.client.rpc('receive_purchase_controlled',{p_operation_key:command.operationKey,p_purchase_id:command.purchaseId,p_received_at:command.receivedAt.toISOString(),p_lines:command.lines.map(l=>({purchase_item_id:l.purchaseItemId,quantity_received:l.quantityReceived,final_unit_cost:l.finalUnitCost})),p_notes:command.notes});if(error)throw new Error(`Unable to receive purchase: ${error.message}`);const purchase=await this.getById(command.purchaseId);if(!purchase)throw new Error('Received purchase could not be read.');return purchase;}

}
