create or replace function public.set_delivery_policy_status_controlled(p_operation_key text,p_policy_key text,p_policy_status text,p_source_reference text default null)
returns void language plpgsql security definer set search_path='' as $$ declare v_actor uuid:=auth.uid(); v_source text; begin
 if v_actor is null then raise exception using errcode='42501',message='LIHEN_AUTH_REQUIRED'; end if;
 if not exists(select 1 from public.profiles p where p.id=v_actor and p.authorization_status='ACTIVE' and p.role_code='OWNER') then raise exception using errcode='42501',message='LIHEN_DELIVERY_POLICY_OWNER_REQUIRED'; end if;
 if coalesce(trim(p_operation_key),'')='' then raise exception using errcode='22023',message='LIHEN_OPERATION_KEY_REQUIRED'; end if;
 if p_policy_status not in ('ACTIVE','DISABLED_PENDING_APPROVAL','ARCHIVED') then raise exception using errcode='22023',message='LIHEN_DELIVERY_POLICY_STATUS_INVALID'; end if;
 if exists(select 1 from public.operational_audit_log a where a.module='DELIVERY_POLICY' and a.operation_key=p_operation_key) then return; end if;
 select source_reference into v_source from lihen_private.delivery_service_policies where policy_key=p_policy_key for update;
 if not found then raise exception using errcode='P0002',message='LIHEN_DELIVERY_POLICY_NOT_FOUND'; end if;
 if p_policy_status='ACTIVE' and p_policy_key='SATURDAY_FREE_CALI' then
   if coalesce(nullif(trim(p_source_reference),''),v_source) like 'NO_APPROVED_PUBLIC_SOURCE%' then raise exception using errcode='22023',message='LIHEN_SATURDAY_FREE_APPROVED_SOURCE_REQUIRED'; end if;
   if not exists(select 1 from lihen_private.delivery_slots s where s.policy_key=p_policy_key and s.slot_status='OPEN' and s.service_date>=current_date and extract(isodow from s.service_date)=6 and s.capacity>s.reserved_count) then raise exception using errcode='22023',message='LIHEN_SATURDAY_FREE_CAPACITY_REQUIRED'; end if;
 end if;
 update lihen_private.delivery_service_policies set policy_status=p_policy_status,source_reference=coalesce(nullif(trim(p_source_reference),''),source_reference),updated_at=now() where policy_key=p_policy_key;
 insert into public.operational_audit_log(module,operation_type,operation_key,actor_id,entity_type,metadata) values('DELIVERY_POLICY','SET_STATUS',p_operation_key,v_actor,'DELIVERY_POLICY',jsonb_build_object('policy_key',p_policy_key,'status',p_policy_status)); end $$;
revoke all on function public.set_delivery_policy_status_controlled(text,text,text,text) from public,anon; grant execute on function public.set_delivery_policy_status_controlled(text,text,text,text) to authenticated,postgres;
create or replace function public.release_delivery_slot_reservation_controlled(p_operation_key text,p_reservation_id uuid)
returns void language plpgsql security definer set search_path='' as $$ declare v_actor uuid:=auth.uid(); v_res lihen_private.delivery_slot_reservations%rowtype; begin
 if v_actor is null then raise exception using errcode='42501',message='LIHEN_AUTH_REQUIRED'; end if;
 if not exists(select 1 from public.profiles p where p.id=v_actor and p.authorization_status='ACTIVE' and p.role_code in ('OWNER','ADMIN')) then raise exception using errcode='42501',message='LIHEN_DELIVERY_SLOT_RELEASE_FORBIDDEN'; end if;
 if coalesce(trim(p_operation_key),'')='' then raise exception using errcode='22023',message='LIHEN_OPERATION_KEY_REQUIRED'; end if;
 if exists(select 1 from public.operational_audit_log a where a.module='DELIVERY_SLOT' and a.operation_key=p_operation_key) then return; end if;
 select * into v_res from lihen_private.delivery_slot_reservations r where r.reservation_id=p_reservation_id for update;
 if not found then raise exception using errcode='P0002',message='LIHEN_DELIVERY_RESERVATION_NOT_FOUND'; end if;
 if v_res.reservation_status='RESERVED' then update lihen_private.delivery_slot_reservations set reservation_status='RELEASED',updated_at=now() where reservation_id=p_reservation_id; update lihen_private.delivery_slots set reserved_count=greatest(reserved_count-1,0),updated_at=now() where slot_id=v_res.slot_id; end if;
 insert into public.operational_audit_log(module,operation_type,operation_key,actor_id,entity_type,entity_id,metadata) values('DELIVERY_SLOT','RELEASE',p_operation_key,v_actor,'DELIVERY_SLOT_RESERVATION',p_reservation_id,jsonb_build_object('slot_id',v_res.slot_id,'order_id',v_res.order_id)); end $$;
revoke all on function public.release_delivery_slot_reservation_controlled(text,uuid) from public,anon; grant execute on function public.release_delivery_slot_reservation_controlled(text,uuid) to authenticated,postgres;
create or replace view lihen_private.qa_e_delivery_saturday_free_closure as
with policies as (select count(*) filter(where policy_key='STANDARD_NATIONAL' and policy_status='ACTIVE' and free_shipping_threshold=100000)::int standard_policy,count(*) filter(where policy_key='SATURDAY_FREE_CALI' and policy_status='DISABLED_PENDING_APPROVAL' and applies_weekday=6)::int saturday_safe_default from lihen_private.delivery_service_policies),
funcs as (select count(*) filter(where proname='get_storefront_delivery_policy_controlled')::int public_policy_rpc,count(*) filter(where proname='configure_delivery_slot_controlled')::int slot_config_rpc,count(*) filter(where proname='reserve_delivery_slot_controlled')::int reserve_rpc,count(*) filter(where proname='release_delivery_slot_reservation_controlled')::int release_rpc,count(*) filter(where proname='set_delivery_policy_status_controlled')::int policy_status_rpc from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and proname in ('get_storefront_delivery_policy_controlled','configure_delivery_slot_controlled','reserve_delivery_slot_controlled','release_delivery_slot_reservation_controlled','set_delivery_policy_status_controlled')),
slots as (select count(*)::int slots,count(*) filter(where reserved_count>capacity)::int overbooked from lihen_private.delivery_slots),style as (select count(*) filter(where status='ACTIVE' and visible_on_website)::int style_visible from public.products where business_line='STYLE')
select case when p.standard_policy=1 and p.saturday_safe_default=1 and f.public_policy_rpc=1 and f.slot_config_rpc=1 and f.reserve_rpc=1 and f.release_rpc=1 and f.policy_status_rpc=1 and s.overbooked=0 and st.style_visible=0 then 'PASS' else 'BLOCKED' end closure_status,p.standard_policy,p.saturday_safe_default,f.public_policy_rpc,f.slot_config_rpc,f.reserve_rpc,s.slots,s.overbooked,st.style_visible,'OPERATIONAL_CAPACITY_READY_SATURDAY_PROMO_PENDING_APPROVED_RULE'::text closure_mode,jsonb_build_array('STANDARD_FREE_SHIPPING_THRESHOLD_100000','DELIVERY_SLOT_CAPACITY_GUARD','NO_DOUBLE_ACTIVE_SLOT_PER_ORDER','IDEMPOTENT_RESERVATION_OPERATION_KEY','RESERVATION_RELEASE_RESTORES_CAPACITY','OWNER_ONLY_SATURDAY_ACTIVATION','APPROVED_SOURCE_AND_FUTURE_CAPACITY_REQUIRED_FOR_SATURDAY','SATURDAY_FREE_NOT_PUBLIC_UNTIL_APPROVED','NO_PRODUCTION_WRITES') contract,f.release_rpc,f.policy_status_rpc from policies p cross join funcs f cross join slots s cross join style st;
insert into lihen_private.phase_exit_gate_results(phase_code,status,gate_version,metrics,accepted_waivers,notes,evaluated_at)
select 'QA-E',case when closure_status='PASS' then 'PASS' else 'BLOCKED' end,'QA_E_DELIVERY_SATURDAY_FREE_SAFETY_CLOSURE_V2',jsonb_build_object('closure_mode',closure_mode,'standard_policy',standard_policy,'saturday_safe_default',saturday_safe_default,'public_policy_rpc',public_policy_rpc,'slot_config_rpc',slot_config_rpc,'reserve_rpc',reserve_rpc,'release_rpc',release_rpc,'policy_status_rpc',policy_status_rpc,'slots',slots,'overbooked',overbooked,'style_visible',style_visible,'contract',contract),jsonb_build_array('SATURDAY_FREE_PUBLIC_ACTIVATION_REQUIRES_APPROVED_COMMERCIAL_RULE_AND_CONFIGURED_CAPACITY'),'QA-E V2 adds controlled slot release and OWNER-only Saturday activation guarded by approved source and future capacity.',now()
from lihen_private.qa_e_delivery_saturday_free_closure
on conflict(phase_code) do update set status=excluded.status,gate_version=excluded.gate_version,metrics=excluded.metrics,accepted_waivers=excluded.accepted_waivers,notes=excluded.notes,evaluated_at=excluded.evaluated_at;
