create or replace view public.catalog_pdf_render_projection with (security_invoker=true) as
select cv.id catalog_version_id,cv.code catalog_code,cv.title catalog_title,cv.version_label,cv.status catalog_status,cv.effective_at,cv.activated_at,e.id catalog_entry_id,e.product_id,e.product_sku_snapshot sku,e.catalog_code_snapshot product_catalog_code,e.slug_snapshot slug,e.product_name_snapshot product_name,e.business_line_snapshot business_line,e.brand_snapshot brand,e.category_snapshot category,e.subcategory_snapshot subcategory,e.description_snapshot description,e.sale_price_snapshot sale_price,e.image_id_snapshot image_id,e.image_url_snapshot image_url,e.image_alt_snapshot image_alt,e.sort_order,e.product_updated_at_snapshot,e.created_at snapshot_created_at from public.catalog_versions cv join public.catalog_entries e on e.catalog_version_id=cv.id where e.visible;
revoke all on public.catalog_pdf_render_projection from public,anon; grant select on public.catalog_pdf_render_projection to authenticated;
create or replace view public.catalog_version_summary with (security_invoker=true) as select cv.id,cv.code,cv.title,cv.version_label,cv.source_type,cv.status,cv.effective_at,cv.created_at,cv.activated_at,cv.archived_at,count(e.id) total_entries,count(e.id) filter(where e.visible) visible_entries,count(e.id) filter(where e.visible and btrim(e.image_url_snapshot)<>'') visible_with_image,count(e.id) filter(where e.visible and e.sale_price_snapshot>=0) visible_with_valid_price from public.catalog_versions cv left join public.catalog_entries e on e.catalog_version_id=cv.id group by cv.id;
revoke all on public.catalog_version_summary from public,anon; grant select on public.catalog_version_summary to authenticated;
create or replace function public.get_pdf_catalog_readiness_controlled(p_catalog_version_id uuid) returns table(catalog_version_id uuid,catalog_status text,visible_entries bigint,failed_checks bigint,readiness text,readiness_reason text) language plpgsql security definer set search_path='' as $function$
declare v_actor uuid:=auth.uid(); v_status text; v_entries bigint; v_failures bigint;
begin if v_actor is null then raise exception using errcode='42501',message='LIHEN_AUTH_REQUIRED'; end if; if not exists(select 1 from public.profiles p where p.id=v_actor and p.authorization_status='ACTIVE' and p.role_code in ('OWNER','ADMIN','OPERATOR','VIEWER')) then raise exception using errcode='42501',message='LIHEN_CATALOG_READ_FORBIDDEN'; end if; select cv.status into v_status from public.catalog_versions cv where cv.id=p_catalog_version_id; if v_status is null then raise exception using errcode='P0002',message='LIHEN_CATALOG_VERSION_NOT_FOUND'; end if; select count(*) into v_entries from public.catalog_entries e where e.catalog_version_id=p_catalog_version_id and e.visible; select count(*) into v_failures from public.validate_pdf_catalog_version_controlled(p_catalog_version_id)v where v.status='FAIL'; return query select p_catalog_version_id,v_status,v_entries,v_failures,case when v_status in('ACTIVE','ARCHIVED') and v_failures=0 and v_entries>0 then 'READY' else 'BLOCKED' end,case when v_entries=0 then 'CATALOG_HAS_NO_VISIBLE_ENTRIES' when v_failures>0 then 'CATALOG_VALIDATION_FAILED' when v_status='DRAFT' then 'CATALOG_NOT_ACTIVATED' when v_status in('ACTIVE','ARCHIVED') then 'CATALOG_RENDER_READY' else 'CATALOG_STATUS_UNSUPPORTED' end; end; $function$;
revoke all on function public.get_pdf_catalog_readiness_controlled(uuid) from public,anon; grant execute on function public.get_pdf_catalog_readiness_controlled(uuid) to authenticated;
comment on view public.catalog_pdf_render_projection is 'Immutable PDF render projection backed only by catalog snapshot fields. No live Product Master join.';
