-- FASE 2.9A: observabilidad de integridad transversal, solo lectura.
create or replace view public.operational_integrity_checks with(security_invoker=true) as
select 'NEGATIVE_ON_HAND'::text check_code,count(*)::bigint issue_count,case when count(*)=0 then 'PASS' else 'FAIL' end::text status from public.inventory_stock where stock_on_hand<0
union all select 'NEGATIVE_AVAILABLE',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.inventory_stock where stock_available<0
union all select 'NEGATIVE_RESERVED',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.inventory_stock where stock_reserved<0
union all select 'NEGATIVE_PENDING',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.inventory_stock where stock_pending<0
union all select 'COMPLETED_ORDER_WITHOUT_SALE',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.orders o where o.status='COMPLETED' and not exists(select 1 from public.sales s where s.order_id=o.id)
union all select 'SALE_ORDER_NOT_COMPLETED',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.sales s join public.orders o on o.id=s.order_id where s.order_id is not null and s.status='COMPLETED' and o.status<>'COMPLETED'
union all select 'SALE_TOTAL_MISMATCH',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.sales s where s.total_amount is distinct from(select coalesce(sum(si.quantity*si.unit_price),0::numeric) from public.sale_items si where si.sale_id=s.id)
union all select 'SALE_FINANCE_MISMATCH',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.sales s where s.status='COMPLETED' and not exists(select 1 from public.financial_movements fm where fm.reference_type='SALE' and fm.reference_id=s.id and fm.movement_type='SALE_INCOME' and fm.amount_signed=s.total_amount and fm.account_id=s.financial_account_id)
union all select 'TRANSFER_PAIR_UNBALANCED',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from(select fm.reference_id from public.financial_movements fm where fm.reference_type='TRANSFER' and fm.reference_id is not null and fm.movement_type in('TRANSFER_IN','TRANSFER_OUT') group by fm.reference_id having count(*)<>2 or coalesce(sum(fm.amount_signed),0)<>0)x
union all select 'RECEIVED_PURCHASE_INCOMPLETE',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.purchases p where p.status='RECEIVED' and exists(select 1 from public.purchase_items pi where pi.purchase_id=p.id and pi.quantity_received<>pi.quantity_requested)
union all select 'PURCHASE_PENDING_MISMATCH',count(*)::bigint,case when count(*)=0 then 'PASS' else 'FAIL' end from public.purchases p where p.status in('CONFIRMED','PARTIALLY_RECEIVED','RECEIVED') and(select coalesce(sum(pi.quantity_requested-pi.quantity_received),0)::bigint from public.purchase_items pi where pi.purchase_id=p.id)is distinct from(select coalesce(sum(im.quantity_delta),0)::bigint from public.inventory_movements im where im.bucket='PENDING_IN' and im.external_reference=p.purchase_number);
revoke all on public.operational_integrity_checks from anon,authenticated;grant select on public.operational_integrity_checks to authenticated;
