create or replace function public.guard_catalog_version_mutation() returns trigger language plpgsql security definer set search_path='' as $function$
declare v_core_changed boolean; v_artifact_changed boolean;
begin
 if tg_op='DELETE' and old.status<>'DRAFT' then raise exception using errcode='55000',message='LIHEN_CATALOG_VERSION_IMMUTABLE'; end if;
 if tg_op='UPDATE' then
  v_core_changed:=new.code is distinct from old.code or new.title is distinct from old.title or new.version_label is distinct from old.version_label or new.source_type is distinct from old.source_type or new.effective_at is distinct from old.effective_at or new.source_reference is distinct from old.source_reference or new.created_by is distinct from old.created_by or new.activated_at is distinct from old.activated_at or new.activated_by is distinct from old.activated_by;
  v_artifact_changed:=new.artifact_url is distinct from old.artifact_url or new.artifact_sha256 is distinct from old.artifact_sha256 or new.artifact_page_count is distinct from old.artifact_page_count or new.renderer_version is distinct from old.renderer_version or new.artifact_generated_at is distinct from old.artifact_generated_at or new.artifact_registered_by is distinct from old.artifact_registered_by;
  if old.status='ACTIVE' then
   if v_core_changed then raise exception using errcode='55000',message='LIHEN_CATALOG_VERSION_IMMUTABLE'; end if;
   if new.status='ACTIVE' then if old.artifact_sha256 is not null or not v_artifact_changed or new.artifact_sha256 is null or new.archived_at is distinct from old.archived_at then raise exception using errcode='55000',message='LIHEN_CATALOG_VERSION_IMMUTABLE'; end if;
   elsif new.status='ARCHIVED' then if v_artifact_changed then raise exception using errcode='55000',message='LIHEN_CATALOG_VERSION_IMMUTABLE'; end if;
   else raise exception using errcode='55000',message='LIHEN_CATALOG_VERSION_IMMUTABLE'; end if;
  elsif old.status='ARCHIVED' then raise exception using errcode='55000',message='LIHEN_CATALOG_VERSION_IMMUTABLE'; end if;
  new.updated_at:=now();
 end if;
 if tg_op='DELETE' then return old; end if; return new;
end; $function$;
revoke all on function public.guard_catalog_version_mutation() from public,anon,authenticated;

create or replace function public.register_pdf_catalog_artifact_controlled(p_catalog_version_id uuid,p_artifact_url text,p_artifact_sha256 text,p_page_count integer,p_renderer_version text) returns void language plpgsql security definer set search_path='' as $function$
declare v_actor uuid:=auth.uid(); v_status text; v_existing_sha text;
begin if v_actor is null then raise exception using errcode='42501',message='LIHEN_AUTH_REQUIRED'; end if; if not exists(select 1 from public.profiles p where p.id=v_actor and p.authorization_status='ACTIVE' and p.role_code in('OWNER','ADMIN')) then raise exception using errcode='42501',message='LIHEN_CATALOG_WRITE_FORBIDDEN'; end if; select cv.status,cv.artifact_sha256 into v_status,v_existing_sha from public.catalog_versions cv where cv.id=p_catalog_version_id for update; if v_status is null then raise exception using errcode='P0002',message='LIHEN_CATALOG_VERSION_NOT_FOUND'; end if; if v_status<>'ACTIVE' then raise exception using errcode='55000',message='LIHEN_CATALOG_ARTIFACT_REQUIRES_ACTIVE_VERSION'; end if; if v_existing_sha is not null then raise exception using errcode='55000',message='LIHEN_CATALOG_ARTIFACT_ALREADY_REGISTERED'; end if; if nullif(btrim(p_artifact_url),'') is null then raise exception using errcode='22023',message='LIHEN_CATALOG_ARTIFACT_URL_REQUIRED'; end if; if lower(btrim(p_artifact_sha256)) !~ '^[0-9a-f]{64}$' then raise exception using errcode='22023',message='LIHEN_CATALOG_ARTIFACT_SHA256_INVALID'; end if; if p_page_count is null or p_page_count<=0 then raise exception using errcode='22023',message='LIHEN_CATALOG_ARTIFACT_PAGE_COUNT_INVALID'; end if; if nullif(btrim(p_renderer_version),'') is null then raise exception using errcode='22023',message='LIHEN_CATALOG_RENDERER_VERSION_REQUIRED'; end if; update public.catalog_versions set artifact_url=btrim(p_artifact_url),artifact_sha256=lower(btrim(p_artifact_sha256)),artifact_page_count=p_page_count,renderer_version=btrim(p_renderer_version),artifact_generated_at=now(),artifact_registered_by=v_actor where id=p_catalog_version_id; insert into public.domain_events(id,event_type,aggregate_type,aggregate_id,occurred_at,actor_id,payload,metadata) values(gen_random_uuid(),'CATALOG_PDF_ARTIFACT_REGISTERED','CATALOG_VERSION',p_catalog_version_id,now(),v_actor,jsonb_build_object('sha256',lower(btrim(p_artifact_sha256)),'page_count',p_page_count,'renderer_version',btrim(p_renderer_version)),jsonb_build_object('phase','4')); end; $function$;
revoke all on function public.register_pdf_catalog_artifact_controlled(uuid,text,text,integer,text) from public,anon; grant execute on function public.register_pdf_catalog_artifact_controlled(uuid,text,text,integer,text) to authenticated;
