create or replace view lihen_private.qa_cde_final_closure as
with gates as (select count(*) filter(where phase_code in ('QA-C','QA-D','QA-E'))::int required_gates,count(*) filter(where phase_code in ('QA-C','QA-D','QA-E') and status='PASS')::int passed_gates from lihen_private.phase_exit_gate_results),
style as (select count(*) filter(where status='ACTIVE' and visible_on_website)::int style_visible from public.products where business_line='STYLE'),
ops as (select count(*) filter(where execution_enabled=false)::int execution_disabled from lihen_private.control_center_operation_catalog)
select case when g.required_gates=3 and g.passed_gates=3 and s.style_visible=0 and o.execution_disabled=14 then 'PASS' else 'BLOCKED' end closure_status,g.required_gates,g.passed_gates,s.style_visible,o.execution_disabled,'QA_C_D_E_CLOSED_SOURCE_BACKED_AND_OPERATIONALLY_GUARDED'::text closure_mode,jsonb_build_array('QA_C_PRODUCT_DETAIL_CLOSED','QA_D_INSTITUTIONAL_SOCIAL_LEGAL_CLOSED','QA_E_DELIVERY_SAFETY_CLOSED','NO_FABRICATED_RICHNESS','SATURDAY_FREE_REQUIRES_APPROVED_ACTIVATION','STYLE_REMAINS_HIDDEN','CONTROLLED_EXECUTION_REMAINS_DISABLED','NO_PRODUCTION_WRITES') contract from gates g cross join style s cross join ops o;
revoke all on lihen_private.qa_cde_final_closure from public,anon,authenticated; grant select on lihen_private.qa_cde_final_closure to postgres;
insert into lihen_private.phase_exit_gate_results(phase_code,status,gate_version,metrics,accepted_waivers,notes,evaluated_at)
select 'QA-CDE',case when closure_status='PASS' then 'PASS' else 'BLOCKED' end,'QA_CDE_FINAL_CLOSURE_V1',jsonb_build_object('closure_mode',closure_mode,'required_gates',required_gates,'passed_gates',passed_gates,'style_visible',style_visible,'execution_disabled',execution_disabled,'contract',contract),jsonb_build_array('QA-C content coverage remains progressive by verified source','QA-E Saturday-free activation waits for approved commercial rule and configured capacity'),'QA-C, QA-D and QA-E are jointly closed at capability/safety level without fabricating product richness or publishing an unapproved Saturday-free promotion.',now()
from lihen_private.qa_cde_final_closure
on conflict(phase_code) do update set status=excluded.status,gate_version=excluded.gate_version,metrics=excluded.metrics,accepted_waivers=excluded.accepted_waivers,notes=excluded.notes,evaluated_at=excluded.evaluated_at;
