-- ============================================================
-- LIHEN CUSTOMER BENEFIT — PERSISTENCE FOUNDATION
-- Candidate migration only.
--
-- IMPORTANT:
--   - Do not apply automatically.
--   - No Orders/Sales/Inventory/Finance mutation.
--   - No automatic discount application.
--   - No automatic WhatsApp send.
--   - No redemption implementation in this foundation.
--   - PROD remains HOLD.
-- ============================================================


-- ============================================================
-- 1. CANONICAL CUSTOMER BENEFITS TABLE
-- ============================================================

create table if not exists public.customer_benefits (
  id uuid primary key default gen_random_uuid(),

  customer_id uuid not null
    references public.customers(id)
    on delete restrict,

  benefit_code text not null,

  business_line text not null
    check (
      business_line in (
        'BEAUTY_CARE',
        'STYLE'
      )
    ),

  benefit_type text not null
    check (
      benefit_type in (
        'WELCOME',
        'RETURN_AFTER_EXPIRED',
        'PURCHASE_THRESHOLD'
      )
    ),

  discount_percent numeric(5,2) not null
    check (
      discount_percent > 0
      and discount_percent <= 100
    ),

  status text not null default 'GENERATED'
    check (
      status in (
        'GENERATED',
        'ACTIVE',
        'REDEEMED',
        'EXPIRED',
        'CANCELLED'
      )
    ),

  eligibility_reason text not null
    check (
      length(btrim(eligibility_reason)) > 0
    ),

  source_order_id uuid null
    references public.orders(id)
    on delete restrict,

  source_sale_id uuid null
    references public.sales(id)
    on delete restrict,

  redeemed_order_id uuid null
    references public.orders(id)
    on delete restrict,

  redeemed_sale_id uuid null
    references public.sales(id)
    on delete restrict,

  created_at timestamptz not null default now(),
  created_by uuid not null,

  issued_at timestamptz null,
  valid_from timestamptz null,
  valid_until timestamptz null,

  redeemed_at timestamptz null,
  cancelled_at timestamptz null,

  policy_snapshot jsonb not null
    default '{}'::jsonb,

  metadata jsonb not null
    default '{}'::jsonb,

  constraint customer_benefits_code_not_blank
    check (
      length(btrim(benefit_code)) > 0
    ),

  constraint customer_benefits_validity_order
    check (
      valid_from is null
      or valid_until is null
      or valid_until > valid_from
    ),

  constraint customer_benefits_active_temporal_state
    check (
      status <> 'ACTIVE'
      or (
        issued_at is not null
        and valid_from is not null
        and valid_until is not null
      )
    ),

  constraint customer_benefits_redeemed_state
    check (
      status <> 'REDEEMED'
      or redeemed_at is not null
    ),

  constraint customer_benefits_cancelled_state
    check (
      status <> 'CANCELLED'
      or cancelled_at is not null
    ),

  constraint customer_benefits_terminal_state_exclusive
    check (
      not (
        redeemed_at is not null
        and cancelled_at is not null
      )
    )
);


comment on table public.customer_benefits is
  'Canonical LIHEN customer benefit history. Benefits are customer-owned commercial records with immutable historical codes and no hard-delete workflow.';


comment on column public.customer_benefits.customer_id is
  'Canonical Customer Master identity. Never replace with phone or name identity.';


comment on column public.customer_benefits.benefit_code is
  'Unique customer benefit code. Final codes must be generated by a future controlled database write path, never by React.';


comment on column public.customer_benefits.policy_snapshot is
  'Snapshot of the commercial policy used when the benefit was issued so historical benefits are not reinterpreted after policy changes.';


-- ============================================================
-- 2. INDEXES
-- ============================================================

create unique index if not exists
  customer_benefits_code_uidx
on public.customer_benefits (
  benefit_code
);


create index if not exists
  customer_benefits_customer_created_idx
on public.customer_benefits (
  customer_id,
  created_at desc
);


create index if not exists
  customer_benefits_customer_line_status_idx
on public.customer_benefits (
  customer_id,
  business_line,
  status
);


create index if not exists
  customer_benefits_active_expiry_idx
on public.customer_benefits (
  valid_until
)
where status = 'ACTIVE';


create index if not exists
  customer_benefits_source_sale_idx
on public.customer_benefits (
  source_sale_id
)
where source_sale_id is not null;


create index if not exists
  customer_benefits_redeemed_sale_idx
on public.customer_benefits (
  redeemed_sale_id
)
where redeemed_sale_id is not null;


-- ============================================================
-- IMPORTANT HOLD:
--
-- Do NOT add a partial unique index limiting GENERATED/ACTIVE
-- benefits per customer/business_line until the commercial rule
-- about simultaneous benefits is explicitly frozen.
-- ============================================================


-- ============================================================
-- 3. RLS — READ OWNER/ADMIN, NO DIRECT WRITES
-- ============================================================

alter table public.customer_benefits
  enable row level security;


revoke all
on table public.customer_benefits
from public, anon, authenticated;


grant select
on table public.customer_benefits
to authenticated;


drop policy if exists
  customer_benefits_owner_admin_read
on public.customer_benefits;


create policy
  customer_benefits_owner_admin_read
on public.customer_benefits
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = (
      select auth.uid()
    )
      and p.authorization_status = 'ACTIVE'
      and p.role_code in (
        'OWNER',
        'ADMIN'
      )
  )
);


-- ============================================================
-- 4. EXTEND EXISTING CUSTOMER WRITE LEDGER CONTRACT
--
-- This foundation only expands the allowed operation vocabulary.
-- It does NOT add a browser write RPC yet.
-- ============================================================

alter table
  lihen_private.customer_write_operations
drop constraint if exists
  customer_write_operations_type_valid;


alter table
  lihen_private.customer_write_operations
add constraint
  customer_write_operations_type_valid
check (
  operation_type in (
    'CREATE_CUSTOMER',
    'UPDATE_CUSTOMER',
    'ASSIGN_ORDER_CUSTOMER',
    'ISSUE_CUSTOMER_BENEFIT',
    'ACTIVATE_CUSTOMER_BENEFIT',
    'REDEEM_CUSTOMER_BENEFIT',
    'EXPIRE_CUSTOMER_BENEFIT',
    'CANCEL_CUSTOMER_BENEFIT'
  )
);


comment on table
lihen_private.customer_write_operations
is
  'Existing Customer Master controlled-write idempotency ledger. Customer Benefit operations reuse this ledger; no parallel benefit operation ledger is introduced.';


-- ============================================================
-- 5. AUDIT TIMELINE REUSE
--
-- Existing DEV architecture already includes
-- lihen_private.customer_write_operations in
-- lihen_private.control_center_operation_audit_timeline under
-- domain_code CUSTOMERS.
--
-- No second timeline is created here.
-- No trigger is added to public.operational_audit_log here.
-- ============================================================


-- ============================================================
-- 6. EXPLICITLY DEFER CONTROLLED MUTATION RPCs
--
-- Future migrations may add:
--
--   public.issue_customer_benefit_controlled(...)
--   public.activate_customer_benefit_controlled(...)
--   public.cancel_customer_benefit_controlled(...)
--
-- only after unresolved commercial rules are frozen.
--
-- Redemption and automatic expiry remain later phases.
-- ============================================================


-- ============================================================
-- 7. EXPLICIT NON-GOALS / BOUNDARIES
-- ============================================================

comment on table public.customer_benefits is
  'Canonical LIHEN customer benefit history. Foundation only: direct writes denied, no auto-discount, no auto-redemption, no auto-expiry, no auto-send, and no Orders/Sales/Inventory/Finance mutation.';


-- ============================================================
-- END
-- ============================================================
