export * from './domain/business-line';
export * from './domain/product';
export * from './domain/product-status';
export * from './domain/errors/product-errors';
export * from './ports/product-repository';
export * from './infrastructure/in-memory-product-repository';
export * from './infrastructure/legacy-product-row';
export * from './infrastructure/legacy-product-mapper';
export * from './infrastructure/supabase-product-repository';
export * from './infrastructure/controlled-product-write-mapper';
export * from './application/dto/product-list-item.dto';
export * from './application/dto/product-detail.dto';
export * from './application/queries/get-products.query';
export * from './application/queries/get-products.handler';
export * from './application/queries/get-product-by-id.query';
export * from './application/queries/get-product-by-id.handler';
export * from './application/commands/create-product.command';
export * from './application/commands/create-product.handler';
export * from './application/commands/update-product.command';
export * from './application/commands/update-product.handler';
export * from './domain/product-sale-price-change';
export * from './ports/product-pricing-repository';
export * from './application/dto/product-sale-price-change.dto';
export * from './application/commands/change-product-sale-price.command';
export * from './application/commands/change-product-sale-price.handler';
export * from './application/queries/get-product-sale-price-history.query';
export * from './application/queries/get-product-sale-price-history.handler';
export * from './domain/product-image';
export * from './ports/product-image-repository';
export * from './infrastructure/in-memory-product-image-repository';
export * from './infrastructure/supabase-product-image-repository';
export * from './infrastructure/legacy-main-image-backfill-mapper';
export * from './application/dto/product-image.dto';
export * from './application/commands/add-product-image.command';
export * from './application/commands/add-product-image.handler';
export * from './application/commands/set-main-product-image.command';
export * from './application/commands/set-main-product-image.handler';
export * from './application/queries/get-product-images.query';
export * from './application/queries/get-product-images.handler';

export * from './domain/brand';
export * from './domain/category';
export * from './ports/brand-repository';
export * from './ports/category-repository';
export * from './infrastructure/in-memory-brand-repository';
export * from './infrastructure/in-memory-category-repository';
export { legacyTaxonomyRowSchema, LegacyTaxonomyCandidateMapper, normalizeTaxonomyText as normalizeLegacyTaxonomyText } from './infrastructure/legacy-taxonomy-candidate-mapper';
export type { LegacyTaxonomyCandidate } from './infrastructure/legacy-taxonomy-candidate-mapper';
export * from './application/dto/brand.dto';
export * from './application/dto/category.dto';
export * from './application/queries/get-brands.query';
export * from './application/queries/get-brands.handler';
export * from './application/queries/get-categories.query';
export * from './application/queries/get-categories.handler';

export * from './domain/product-image-storage';
export * from './ports/product-image-storage';
export * from './infrastructure/supabase-product-image-storage';
export * from './domain/catalog-image-reconciliation';
export * from './domain/product-master-reconciliation';
export * from './domain/taxonomy-reconciliation';
export * from './domain/taxonomy-import';

export * from './domain/product-import-candidate';

export * from './domain/approved-product-import';
export * from './domain/full-canonical-product-import';

export * from './domain/web-image-derivative';
export * from './domain/product-media-readiness';
export * from './domain/product-media-source-selection';
export * from './domain/product-media-manifest';
export * from './infrastructure/supabase-brand-repository';
export * from './infrastructure/supabase-category-repository';
export * from './domain/events/product-created.event';
export * from './domain/events/product-sale-price-changed.event';
export * from './strategies/product-import-decision.strategy';

export * from './domain/style-product-readiness';
